### ISSUE TITLE
[ES 6 Preview] Can't start the server in dev mode.

### ISSUE THREAD

**Issue by YoEight** [EventStore/eventstore-docker#72]
Greetings,

We can't start ES 6 Preview server in dev mode, the server just crashes. Here's the command I used:

```
docker run --publish 2113:2113 -e EVENTSTORE_DEV=1 eventstore/eventstore:6.0.0-previ
ew1-bionic
```

The output I got:

```
[00001,01,00:12:27.172]
"ES VERSION:"             "0.0.0.0" ("Unknown"/"Unknown", "Unknown")
[00001,01,00:12:27.210] "OS:"                     Linux (Unix 4.9.184.0)
[00001,01,00:12:27.225] "RUNTIME:"                ".NET 3.1.0" (64-bit)
[00001,01,00:12:27.225] "GC:"                     "3 GENERATIONS"
[00001,01,00:12:27.225] "LOGS:"                   "/var/log/eventstore"
MODIFIED OPTIONS:

        EXT IP:                   0.0.0.0 (Command Line)
        INT IP:                   0.0.0.0 (Command Line)
        DEV:                      1 (Environment Variable)

DEFAULT OPTIONS:

        HELP:                     False (<DEFAULT>)
        VERSION:                  False (<DEFAULT>)
        LOG:                      /var/log/eventstore (<DEFAULT>)
        CONFIG:                   <empty> (<DEFAULT>)
        DEFINES:                  <empty> (<DEFAULT>)
        WHAT IF:                  False (<DEFAULT>)
        START STANDARD PROJECTIONS: False (<DEFAULT>)
        DISABLE HTTP CACHING:     False (<DEFAULT>)
        MONO MIN THREADPOOL SIZE: 10 (<DEFAULT>)
        INT HTTP PORT:            2112 (<DEFAULT>)
        EXT HTTP PORT:            2113 (<DEFAULT>)
        INT TCP PORT:             1112 (<DEFAULT>)
        INT SECURE TCP PORT:      0 (<DEFAULT>)
        EXT TCP PORT:             1113 (<DEFAULT>)
        EXT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        EXT SECURE TCP PORT:      0 (<DEFAULT>)
        EXT IP ADVERTISE AS:      <empty> (<DEFAULT>)
        EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        EXT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT IP ADVERTISE AS:      <empty> (<DEFAULT>)
        INT SECURE TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT HTTP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
        INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
        GOSSIP ON SINGLE NODE:    False (<DEFAULT>)
        CONNECTION PENDING SEND BYTES THRESHOLD: 10485760 (<DEFAULT>)
        CONNECTION QUEUE SIZE THRESHOLD: 50000 (<DEFAULT>)
        FORCE:                    False (<DEFAULT>)
        CLUSTER SIZE:             1 (<DEFAULT>)
        NODE PRIORITY:            0 (<DEFAULT>)
        MIN FLUSH DELAY MS:       2 (<DEFAULT>)
        COMMIT COUNT:             -1 (<DEFAULT>)
        PREPARE COUNT:            -1 (<DEFAULT>)
        ADMIN ON EXT:             True (<DEFAULT>)
        STATS ON EXT:             True (<DEFAULT>)
        GOSSIP ON EXT:            True (<DEFAULT>)
        DISABLE SCAVENGE MERGING: False (<DEFAULT>)
        SCAVENGE HISTORY MAX AGE: 30 (<DEFAULT>)
        DISCOVER VIA DNS:         True (<DEFAULT>)
        CLUSTER DNS:              fake.dns (<DEFAULT>)
        CLUSTER GOSSIP PORT:      30777 (<DEFAULT>)
        GOSSIP SEED:              <empty> (<DEFAULT>)
        STATS PERIOD SEC:         30 (<DEFAULT>)
        CACHED CHUNKS:            -1 (<DEFAULT>)
        READER THREADS COUNT:     4 (<DEFAULT>)
        CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
        MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
        HASH COLLISION READ LIMIT: 100 (<DEFAULT>)
        DB:                       /var/lib/eventstore (<DEFAULT>)
        INDEX:                    <empty> (<DEFAULT>)
        MEM DB:                   False (<DEFAULT>)
        SKIP DB VERIFY:           False (<DEFAULT>)
        WRITE THROUGH:            False (<DEFAULT>)
        UNBUFFERED:               False (<DEFAULT>)
        CHUNK INITIAL READER COUNT: 5 (<DEFAULT>)
        RUN PROJECTIONS:          None (<DEFAULT>)
        PROJECTION THREADS:       3 (<DEFAULT>)
        WORKER THREADS:           5 (<DEFAULT>)
        PROJECTIONS QUERY EXPIRY: 5 (<DEFAULT>)
        FAULT OUT OF ORDER PROJECTIONS: False (<DEFAULT>)
        ENABLE TRUSTED AUTH:      False (<DEFAULT>)
        CERTIFICATE STORE LOCATION: <empty> (<DEFAULT>)
        CERTIFICATE STORE NAME:   <empty> (<DEFAULT>)
        CERTIFICATE SUBJECT NAME: <empty> (<DEFAULT>)
        CERTIFICATE THUMBPRINT:   <empty> (<DEFAULT>)
        CERTIFICATE FILE:         <empty> (<DEFAULT>)
        CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
        USE INTERNAL SSL:         False (<DEFAULT>)
        DISABLE INSECURE TCP:     False (<DEFAULT>)
        SSL TARGET HOST:          n/a (<DEFAULT>)
        SSL VALIDATE SERVER:      True (<DEFAULT>)
        AUTHENTICATION TYPE:      internal (<DEFAULT>)
        AUTHENTICATION CONFIG:    <empty> (<DEFAULT>)
        DISABLE FIRST LEVEL HTTP AUTHORIZATION: False (<DEFAULT>)
        PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
        COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
        UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
        BETTER ORDERING:          False (<DEFAULT>)
        UNSAFE IGNORE HARD DELETE: False (<DEFAULT>)
        SKIP INDEX VERIFY:        False (<DEFAULT>)
        INDEX CACHE DEPTH:        16 (<DEFAULT>)
        OPTIMIZE INDEX MERGE:     False (<DEFAULT>)
        GOSSIP INTERVAL MS:       1000 (<DEFAULT>)
        GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
        GOSSIP TIMEOUT MS:        500 (<DEFAULT>)
        READ ONLY REPLICA:        False (<DEFAULT>)
        ENABLE HISTOGRAMS:        False (<DEFAULT>)
        LOG HTTP REQUESTS:        False (<DEFAULT>)
        LOG FAILED AUTHENTICATION ATTEMPTS: False (<DEFAULT>)
        ALWAYS KEEP SCAVENGED:    False (<DEFAULT>)
        SKIP INDEX SCAN ON READS: False (<DEFAULT>)
        REDUCE FILE CACHE PRESSURE: False (<DEFAULT>)
        INITIALIZATION THREADS:   1 (<DEFAULT>)
        STRUCTURED LOG:           True (<DEFAULT>)
        MAX AUTO MERGE INDEX LEVEL: 2147483647 (<DEFAULT>)
        WRITE STATS TO DB:        False (<DEFAULT>)
        MAX APPEND SIZE:          1048576 (<DEFAULT>)

[00001,01,00:12:27.245] {"defaults":{"Help":"False","Version":"False","Log":"\/var\/log\/eventstore","Config":"",
"Defines":"System.String[]","WhatIf":"False","StartStandardProjections":"False","DisableHTTPCaching":"False","Mon
oMinThreadpoolSize":"10","IntHttpPort":"2112","ExtHttpPort":"2113","IntTcpPort":"1112","IntSecureTcpPort":"0","Ex
tTcpPort":"1113","ExtSecureTcpPortAdvertiseAs":"0","ExtSecureTcpPort":"0","ExtIpAdvertiseAs":null,"ExtTcpPortAdve
rtiseAs":"0","ExtHttpPortAdvertiseAs":"0","IntIpAdvertiseAs":null,"IntSecureTcpPortAdvertiseAs":"0","IntTcpPortAd
vertiseAs":"0","IntHttpPortAdvertiseAs":"0","IntTcpHeartbeatTimeout":"700","ExtTcpHeartbeatTimeout":"1000","IntTc
pHeartbeatInterval":"700","ExtTcpHeartbeatInterval":"2000","GossipOnSingleNode":"False","ConnectionPendingSendByt
esThreshold":"10485760","ConnectionQueueSizeThreshold":"50000","Force":"False","ClusterSize":"1","NodePriority":"
0","MinFlushDelayMs":"2","CommitCount":"-1","PrepareCount":"-1","AdminOnExt":"True","StatsOnExt":"True","GossipOn
Ext":"True","DisableScavengeMerging":"False","ScavengeHistoryMaxAge":"30","DiscoverViaDns":"True","ClusterDns":"f
ake.dns","ClusterGossipPort":"30777","GossipSeed":"System.Net.IPEndPoint[]","StatsPeriodSec":"30","CachedChunks":
"-1","ReaderThreadsCount":"4","ChunksCacheSize":"536871424","MaxMemTableSize":"1000000","HashCollisionReadLimit":
"100","Db":"\/var\/lib\/eventstore","Index":null,"MemDb":"False","SkipDbVerify":"False","WriteThrough":"False","U
nbuffered":"False","ChunkInitialReaderCount":"5","RunProjections":"None","ProjectionThreads":"3","WorkerThreads":
"5","ProjectionsQueryExpiry":"5","FaultOutOfOrderProjections":"False","EnableTrustedAuth":"False","CertificateSto
reLocation":"","CertificateStoreName":"","CertificateSubjectName":"","CertificateThumbprint":"","CertificateFile"
:"","CertificatePassword":"","UseInternalSsl":"False","DisableInsecureTCP":"False","SslTargetHost":"n\/a","SslVal
idateServer":"True","AuthenticationType":"internal","AuthenticationConfig":"","DisableFirstLevelHttpAuthorization
":"False","PrepareTimeoutMs":"2000","CommitTimeoutMs":"2000","UnsafeDisableFlushToDisk":"False","BetterOrdering":
"False","UnsafeIgnoreHardDelete":"False","SkipIndexVerify":"False","IndexCacheDepth":"16","OptimizeIndexMerge":"F
alse","GossipIntervalMs":"1000","GossipAllowedDifferenceMs":"60000","GossipTimeoutMs":"500","ReadOnlyReplica":"Fa
lse","EnableHistograms":"False","LogHttpRequests":"False","LogFailedAuthenticationAttempts":"False","AlwaysKeepSc
avenged":"False","SkipIndexScanOnReads":"False","ReduceFileCachePressure":"False","InitializationThreads":"1","St
ructuredLog":"True","MaxAutoMergeIndexLevel":"2147483647","WriteStatsToDb":"False","MaxAppendSize":"1048576"},"mo
dified":{"ExtIp":"0.0.0.0","IntIp":"0.0.0.0","Dev":"1"}}
[00001,01,00:12:27.254]
========================================================================================================
DEVELOPMENT MODE IS ON. THIS MODE IS *NOT* INTENDED FOR PRODUCTION USE.
WHEN IN DEVELOPMENT MODE EVENT STORE WILL
 - NOT WRITE ANY DATA TO DISK.
 - USE A SELF SIGNED CERTIFICATE.
========================================================================================================

[00001,01,00:12:27.273] Quorum size set to 1
[00001,01,00:12:27.283] Cannot find plugins path: "/usr/share/eventstore/plugins"
[00001,01,00:12:27.556] MessageHierarchy initialization took 00:00:00.2231631.
[00001,01,00:12:27.592] "INSTANCE ID:"            0640bb3a-31e5-41f7-87fc-830af3926ab2
[00001,01,00:12:27.592] "DATABASE:"               "/var/lib/eventstore"
[00001,01,00:12:27.592] "WRITER CHECKPOINT:"      0 (0x0)
[00001,01,00:12:27.605] "CHASER CHECKPOINT:"      0 (0x0)
[00001,01,00:12:27.605] "EPOCH CHECKPOINT:"       -1 (0xFFFFFFFFFFFFFFFF)
[00001,01,00:12:27.605] "TRUNCATE CHECKPOINT:"    -1 (0xFFFFFFFFFFFFFFFF)
[00001,01,00:12:27.666] Could not create performance counter: category='"Processor"', counter='"% Processor Time"
', instance='"_Total"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='"Memory"', counter='"Available Bytes"', i
nstance='""'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='"Process"', counter='"% Processor Time"',
 instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='"Process"', counter='"Thread Count"', ins
tance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Exceptions"', counter='"# of Ex
ceps Thrown / sec"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR LocksAndThreads"', counter='"Co
ntention Rate / sec"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"# Gen 0 Col
lections"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"# Gen 1 Col
lections"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"# Gen 2 Col
lections"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"Gen 0 heap
size"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"Gen 1 heap
size"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"Gen 2 heap
size"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"Large Objec
t Heap size"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"Allocated B
ytes/sec"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"% Time in G
C"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.666] Could not create performance counter: category='".NET CLR Memory"', counter='"# Bytes in
all Heaps"', instance='"1"'. Error: "Performance Counters are not supported on this platform."
[00001,01,00:12:27.726] CACHED TFChunk #0-0 (chunk-000000.000000) in 00:00:00.0022672.
[00001,01,00:12:27.837] Starting MiniWeb for "/web/es/js/projections" ==> "/opt/eventstore/projections"
[00001,01,00:12:27.837] Starting MiniWeb for "/web/es/js/projections/v8/Prelude" ==> "/opt/eventstore/Prelude"
[00001,01,00:12:27.846] Starting MiniWeb for "/web" ==> "/opt/eventstore/clusternode-web"
[00001,01,00:12:27.846] Binding MiniWeb to "/web/{*remaining_path}"
[00001,15,00:12:27.955] ========== [0.0.0.0:2112] SYSTEM INIT...
[00001,15,00:12:27.960] Starting "Normal" TCP listening on TCP endpoint: 0.0.0.0:1113.
[00001,20,00:12:27.960] TableIndex initialization...
[00001,20,00:12:27.974] ReadIndex building...
[00001,20,00:12:27.974] ReadIndex rebuilding done: total processed 0 records, time elapsed: 00:00:00.0024264.
Application startup exception: System.ArgumentNullException: Value cannot be null. (Parameter 'serverCertificate'
)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, X509Certifi
cate2 serverCertificate)
   at EventStore.ClusterNode.Program.<>c__DisplayClass10_0.<Create>b__2(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configur
e)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPAddress address, Int32 port, Action`
1 configure)
   at EventStore.ClusterNode.Program.<>c__DisplayClass10_0.<Create>b__0(KestrelServerOptions o)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFact
ory loggerFactory)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, IConnectionListenerFactory
 transportFactory, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean construct
or, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters
, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite
callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite c
allSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lo
ckType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSi
te singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite call
Site, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite call
Site, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<R
ealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, S
erviceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvid
er provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServicePro
vider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
[00001,15,00:12:27.980] ========== [0.0.0.0:2112] Service '"StorageWriter"' initialized.
[00001,15,00:12:27.980] ========== [0.0.0.0:2112] Service '"StorageReader"' initialized.
[00001,15,00:12:27.993] ========== [0.0.0.0:2112] Service '"StorageChaser"' initialized.
[00001,01,00:12:27.980] Application startup exception
EXCEPTION OCCURRED
Value cannot be null. (Parameter 'serverCertificate')
[00001,15,00:12:28.004] ========== [0.0.0.0:2112] SYSTEM START...
[00001,15,00:12:28.004] ========== [0.0.0.0:2112] IS UNKNOWN...
[00001,09,00:12:28.011] Persistent subscriptions received state change to Unknown. Stopping listening
[00001,15,00:12:28.011] ELECTIONS: STARTING ELECTIONS.
[00001,15,00:12:28.027] ELECTIONS: (V=0) SHIFT TO LEADER ELECTION.
[00001,15,00:12:28.031] ELECTIONS: (V=0) VIEWCHANGE FROM [127.0.0.1:2112, {0640bb3a-31e5-41f7-87fc-830af3926ab2}]
.
[00001,15,00:12:28.031] ELECTIONS: (V=0) MAJORITY OF VIEWCHANGE.
[00001,15,00:12:28.031] ELECTIONS: (V=0) SHIFT TO PREPARE PHASE.
[00001,15,00:12:28.031] ELECTIONS: (V=0) PREPARE_OK FROM "[127.0.0.1:2112,{0640bb3a-31e5-41f7-87fc-830af3926ab2}]
(L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000},Priority=0)".
[00001,15,00:12:28.031] ELECTIONS: (V=0) SHIFT TO REG_LEADER.
[00001,15,00:12:28.050] ELECTIONS: (V=0) SENDING PROPOSAL CANDIDATE: "[127.0.0.1:2112,{0640bb3a-31e5-41f7-87fc-83
0af3926ab2}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000},Priority=0)", ME: "[127.0.0.1:2112,{0640b
b3a-31e5-41f7-87fc-830af3926ab2}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000},Priority=0)".
[00001,15,00:12:28.050] ELECTIONS: (V=0) ACCEPT FROM [127.0.0.1:2112,{0640bb3a-31e5-41f7-87fc-830af3926ab2}] M=[1
27.0.0.1:2112,{0640bb3a-31e5-41f7-87fc-830af3926ab2}]).
[00001,15,00:12:28.050] ELECTIONS: (V=0) DONE. ELECTED MASTER = "[127.0.0.1:2112,{0640bb3a-31e5-41f7-87fc-830af39
26ab2}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000},Priority=0)". ME="[127.0.0.1:2112,{0640bb3a-31
e5-41f7-87fc-830af3926ab2}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000},Priority=0)".
[00001,15,00:12:28.060] ========== [0.0.0.0:2112] PRE-MASTER STATE, WAITING FOR CHASER TO CATCH UP...
[00001,05,00:12:28.060] Persistent subscriptions received state change to PreMaster. Stopping listening
[00001,15,00:12:28.073] ========== [0.0.0.0:2112] IS MASTER... SPARTA!
[00001,06,00:12:28.082] Persistent subscriptions Became Master so now handling subscriptions
[00001,15,00:12:28.082] Searching for incomplete scavenges on node "0.0.0.0:2113".
[00001,15,00:12:28.149] SLOW BUS MSG ["MainBus"]: "ReadStreamEventsBackwardCompleted" - 64ms. Handler: "RequestRe
sponseDispatcher`2".
[00001,15,00:12:28.152] SLOW QUEUE MSG ["MainQueue"]: "ReadStreamEventsBackwardCompleted" - 65ms. Q: 2/5.
[00001,15,00:12:28.152] Setting max age for the "$scavenges" stream to 30.00:00:00.
[00001,15,00:12:28.152] Setting $ops read permission for the "$scavenges" stream
[00001,15,00:12:28.166] No incomplete scavenges found on node "0.0.0.0:2113".
[00001,13,00:12:28.251] === Writing E0@0:{ec96ff8d-40e5-4bcb-a527-0d505954a969} (previous epoch at -1).
[00001,13,00:12:28.259] === Update Last Epoch E0@0:{ec96ff8d-40e5-4bcb-a527-0d505954a969} (previous epoch at -1).
[00001,15,00:12:28.401] 'ops' user account has been created.
[00001,15,00:12:28.401] 'admin' user account has been created.
[00001,15,00:12:28.401] 'ops' user added to $users.
[00001,15,00:12:28.411] 'admin' user added to $users.
[00001,23,00:12:28.411] PROJECTIONS SUBSYSTEM: Starting components for Instance: 6af3a184-bdf6-4ad0-9367-1fccbaa6
92ac
[00001,23,00:12:28.411] PROJECTIONS: Projection Core Coordinator component starting. Correlation: 6af3a184-bdf6-4
ad0-9367-1fccbaa692ac
[00001,23,00:12:28.411] PROJECTIONS: Starting Projections Core Coordinator
[00001,23,00:12:28.411] PROJECTIONS: SubComponent Started: "EventReaderCoreService"
[00001,23,00:12:28.420] PROJECTIONS SUBSYSTEM: Component '"ProjectionCoreCoordinator"' started for Instance: 6af3
a184-bdf6-4ad0-9367-1fccbaa692ac
[00001,23,00:12:28.420] PROJECTIONS SUBSYSTEM: All components started for Instance: 6af3a184-bdf6-4ad0-9367-1fccb
aa692ac
[00001,15,00:12:28.420] ========== [0.0.0.0:2112] Sub System '"Projections"' initialized.
[00001,08,00:12:28.420] "Value cannot be null. (Parameter 'serverCertificate')"
EXCEPTION OCCURRED
Value cannot be null. (Parameter 'serverCertificate')
```
Thanks for your time.

**Comment by pgermishuys** [comment]
Hi @YoEight,
EventStore parses the `Dev` (development) option to set a couple of other options. using `true` instead of `1` should work in your case.
e.g.
```
docker run --publish 2113:2113 -e EVENTSTORE_DEV=true eventstore/eventstore:6.0.0-preview1-bionic
```

**Edit**:
The reason `1` generally works as a valid value for boolean options is because Event Store uses an options parsing library called `Rags`.
`Rags` assumes that any value for a property that has a boolean type is `true` unless the value is  `false` or `0`.
See: https://github.com/EventStore/EventStore/blob/master/src/EventStore.Rags/Translators.cs#L9.
The above path is not hit when the `Dev` option's value is intercepted to set the other options (such as the certificate file, certificate password and memory db).

**Comment by YoEight** [comment]
@pgermishuys It worked, Thanks for the explanation!
