### ISSUE TITLE
Documentation: Following pull and run instruction leads to crash

### ISSUE THREAD

**Issue by horsdal** [EventStore/eventstore-docker#82]
I followed the instructions in the readme to `docker pull` and `docker run --name eventstore-node -it -p 2113:2113 -p 1113:1113 eventstore/eventstore` but the image failed during start up with this exception:
```
    1, 1,05:52:34.242,INF] Quorum size set to 1
[    1, 1,05:52:34.245,FTL] Host terminated unexpectedly.
System.Exception: A TLS Certificate is required unless development mode (--dev) is set.
   at EventStore.ClusterNode.ClusterVNodeHostedService.BuildNode(ClusterNodeOptions options) in /build/src/EventStore.ClusterNode/ClusterVNodeHostedService.cs:line 378
   at EventStore.ClusterNode.ClusterVNodeHostedService.Create(ClusterNodeOptions opts) in /build/src/EventStore.ClusterNode/ClusterVNodeHostedService.cs:line 174
   at EventStore.Core.EventStoreHostedService`1..ctor(String[] args) in /build/src/EventStore.Core/EventStoreHostedService.cs:line 43
   at EventStore.ClusterNode.ClusterVNodeHostedService..ctor(String[] args) in /build/src/EventStore.ClusterNode/ClusterVNodeHostedService.cs:line 34
   at EventStore.ClusterNode.Program.Main(String[] args) in /build/src/EventStore.ClusterNode/Program.cs:line 20
```

I solved it by adding `-e EVENTSTORE_DEV=true` to my `docker run`, but I am not sure that's good solution. But I would suggest putting something in the readme about troubleshooting this issue.

This was on a Win10 machine, using Docker Desktop with WSL as backend.

**Comment by pgermishuys** [comment]
Hey @horsdal, thanks for reporting this. We are in the process of archiving this repository and moving all the open issues over to the main [Event Store Db repository](https://github.com/EventStore/EventStore). We will ensure that this issue is documented and made visible in the process.

**Comment by arwinneil** [comment]
Hello,

This issue has been close due to management of Docker builds moving to [EventStore/EventStore](https://github.com/EventStore/EventStore), and this repository is due to be archived. 

The issue has been moved to [EventStore#2650](https://github.com/EventStore/EventStore/issues/2650).

Thank you.
